title: Izumi的个人主页（建设中）
author:
  name: Izumi_Ayaki
  email: izumi_ayaki@qq.com
description: > # this means to ignore newlines until "show_excerpts:"
   

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    - { platform: Weibo,       user_url: "https://weibo.com/u/5679319503" }
    - { platform: bilibili,       user_url: "https://space.bilibili.com/22617205" }
    - { platform: twitter,        user_url: "https://twitter.com/izumi_ayaki" }
    - { platform: youtube,        user_url: "https://www.youtube.com/channel/UCSKRFx1z9myyUwhXQepUlAg" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
